### ISSUE TITLE
小米max android6.0 

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/NewProjectSum#11]

**Comment by HanteIsHante** [comment]
09-06 17:49:31.033 22299-22299/com.example.hante.newprojectsum E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.example.hante.newprojectsum, PID: 22299
                                                                                **java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.hante.newprojectsum/com.example.hante.newprojectsum.activitys.WelcomeActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content**
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                                                     at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5442)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                                                  Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
                                                                                     at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:317)
                                                                                     at com.example.hante.newprojectsum.activitys.WelcomeActivity.onCreate(WelcomeActivity.java:35)
                                                                                     at android.app.Activity.performCreate(Activity.java:6303)
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                                                     at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5442) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
