### ISSUE TITLE
java.lang.IllegalStateException: beginBroadcast() called while already in a broadcast

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/NewProjectSum#83]
>java.lang.IllegalStateException: beginBroadcast() called while already in a broadcast
```
Process: cc.netpas.android_firewall, PID: 17262
 java.lang.IllegalStateException: beginBroadcast() called while already in a broadcast
at android.os.Parcel.readException(Parcel.java:1480)
at android.os.Parcel.readException(Parcel.java:1426)
at net.netfits.android.sdk.INetfitsVpnService$Stub$Proxy.vpnStop(INetfitsVpnService.java:250)
at cc.netpas.android_firewall.service.VpnConnectionService$ConnBinder$1.run(VpnConnectionService.java:223)
at java.lang.Thread.run(Thread.java:841) 
```
任务过重，引起阻塞，上一个任务未执行完，下一个任务便开始执行

**Comment by HanteIsHante** [comment]
新开启个线程将重任务放入执行

**Comment by HanteIsHante** [comment]
`new Thread(new Runnable(){}).start();`

**Comment by HanteIsHante** [comment]
```
 int i = callbacks.beginBroadcast();
 while (i > 0) {
     i--;
     try {
         callbacks.getBroadcastItem(i).somethingHappened();
     } catch (RemoteException e) {
         // The RemoteCallbackList will take care of removing
         // the dead object for us.
     }
 }
 callbacks.finishBroadcast(); 
```

**问题出在**
```
callbacks.getBroadcastItem(i).somethingHappened()
```

**Comment by HanteIsHante** [comment]
[Android Develop](https://developer.android.com/reference/android/os/RemoteCallbackList.html)

**Comment by HanteIsHante** [comment]
**仍然有问题**

**Comment by nealkafuly** [comment]
u must add finally tag to finishBroadcast method

**Comment by nealkafuly** [comment]
finally {
            try{
                mCallbacks.finishBroadcast();
            }catch (Exception e){
                e.printStackTrace();
            }
        }
