### ISSUE TITLE
Android Thread第二次Thread.start()报错的疑问

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/NewProjectSum#84]
```
java.lang.IllegalThreadStateException: Thread already started
                                                                                   at java.lang.Thread.checkNotStarted(Thread.java:871)
                                                                                   at java.lang.Thread.start(Thread.java:1025)
                                                                                   at com.example.hante.threadmodel.MainActivity.onClick(MainActivity.java:38)
                                                                                   at android.view.View.performClick(View.java:4444)
                                                                                   at android.view.View$PerformClick.run(View.java:18440)
                                                                                   at android.os.Handler.handleCallback(Handler.java:733)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:136)
```

可以写一个继承Thread的类，或者写一个Runnable，然后再new Thread(xx).start();就可以了，
新代码如下：

创建一个Runnable，用于Thread执行
```
Runnable sendable = new Runnable() {

		@Override
		public void run() {
			// TODO Auto-generated method stub

		}
	};
```
run方法中写上需要操作的逻辑，然后这样调用：
```
new Thread(sendable).start();
```
这样，**每次需要调用的时候会重新new一个Thread**，大体是这样，但可以无限次数运行。

**Comment by HanteIsHante** [comment]
ok, 解决

**Comment by HanteIsHante** [comment]
```
Thread.interrupt()
```
并不是停止线程而是一种 标识
[通过Thread实例的start()，一个Thread的实例只能产生一个线程](https://zhidao.baidu.com/question/584688188.html?fr=iks&word=Thread+%B5%DA%B6%FE%B4%CE%B5%F7%D3%C3Tread.start%28%29+%B1%A8%B4%ED&ie=gbk)

**Comment by HanteIsHante** [comment]
android开发中，对线程的操作比较悲催，start一个线程后，必须将标志位置false后过一段时间线程才会停止。

当我们再次用到线程的时候，不管Thread.isAlife()返回的是true还是false，如果我们再次Thread.start()，就会下面这样一个错误：
```
 java.lang.IllegalThreadStateException: Thread already started
```

**Comment by HanteIsHante** [comment]
[Developer Thread](https://developer.android.com/reference/java/lang/Thread.html)
