### ISSUE TITLE
Caused by: java.lang.IllegalStateException: beginBroadcast() called while already in a broadcast

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/NewProjectSum#85]
```
 Caused by: java.lang.IllegalStateException: beginBroadcast() called while already in a broadcast
                                                                              at android.os.Parcel.readException(Parcel.java:1480)
                                                                              at android.os.Parcel.readException(Parcel.java:1426)
                                                                              at net.netfits.android.sdk.INetfitsVpnService$Stub$Proxy.vpnStop(INetfitsVpnService.java:250)
                                                                              at cc.netpas.android_firewall.service.VpnConnectionService.vpnStop(VpnConnectionService.java:218)
                                                                              at cc.netpas.android_firewall.logic.vpnmanager.VpnManagerImpl.vpnStop(VpnManagerImpl.java:136)
```

**Comment by HanteIsHante** [comment]
使用 **synchronized**  修饰

**Comment by HanteIsHante** [comment]
用 **synchronized** 修饰下面方法

```
 int i = callbacks.beginBroadcast();
 while (i > 0) {
     i--;
     try {
         callbacks.getBroadcastItem(i).somethingHappened();
     } catch (RemoteException e) {
         // The RemoteCallbackList will take care of removing
         // the dead object for us.
     }
 }
 callbacks.finishBroadcast();

```

**Comment by HanteIsHante** [comment]
[RemoteCallbackList-develop](https://developer.android.com/reference/android/os/RemoteCallbackList.html)
