### ISSUE TITLE
handler Can't create handler inside thread that has not called Looper.prepare():在子线程thread中不能创建handler，没有叫Looper.prepare()的方法。

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/NewProjectSum#86]
```
Core RequestQueue. This is likely unintended, so ignoring.
 FATAL EXCEPTION: Thread-911
 Process: cc.netpas.android_firewall, PID: 13541
 java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
     at android.os.Handler.<init>(Handler.java:200)
     at android.os.Handler.<init>(Handler.java:114)
     at cc.netpas.android_firewall.service.BackgroundDaemon.startTimerFromActivity(BackgroundDaemon.java:544)
     at cc.netpas.android_firewall.service.BackgroundDaemon.onIServiceStarted(BackgroundDaemon.java:126)
     at cc.netpas.android_firewall.logic.vpnmanager.VpnManagerImpl.onIServiceStarted(VpnManagerImpl.java:240)
     at cc.netpas.android_firewall.service.VpnConnectionService$2$1.run(VpnConnectionService.java:76)
     at java.lang.Thread.run(Thread.java:818)
lt: 15
```
**Error Code:**
```
        handler = new Handler();
        handler.postDelayed(updateConnectedTimer, 1000);
```

**Comment by HanteIsHante** [comment]
如果在主线程中创建handler时，系统会自动创建Looper,但是在子线程中创建handler时，是不会自动创建Looper的，此时如果不手动创建Looper，系统就会崩溃

**Comment by HanteIsHante** [comment]
**(1)** Looper类别用来为一个线程开启一个消息循环。默认情况下Android中新诞生的线程是没有开启消息循环的。（主线程除外，主线程系统会自动为其创建Looper对象，开启消息循环）
Looper对象通过MessageQueue来存放消息和事件。一个线程只能有一个Looper，对应一个MessageQueue。

**(2)** 通常是通过Handler对象来与Looper交互的。Handler可看做是Looper的一个接口，用来向指定的Looper发送消息及定义处理方法。
默认情况下Handler会与其被定义时所在线程的Looper绑定，比如，在主线程中定义，其是与主线程的Looper绑定。
mainHandler = new Handler() 等价于new Handler（Looper.myLooper()）.
Looper.myLooper()：Return the Looper object associated with the current thread 获取当前进程的looper对象。
还有一个类似的 Looper.getMainLooper() 用于获取主线程的Looper对象。

**(3)** 在非主线程中直接new Handler() 会报如下的错误:
E/AndroidRuntime( 6173): Uncaught handler: thread Thread-8 exiting due to uncaught exception
E/AndroidRuntime( 6173): java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
原因是非主线程中默认没有创建Looper对象，需要先调用Looper.prepare()启用Looper。
 
**(4)** Looper.loop(); 让Looper开始工作，从消息队列里取消息，处理消息。
注意：写在Looper.loop()之后的代码不会被执行，这个函数内部应该是一个循环，当调用mHandler.getLooper().quit()后，loop才会中止，其后的代码才能得以运行。
