### ISSUE TITLE
java.lang.IllegalArgumentException: Service not registered

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/NewProjectSum#88]
**java.lang.IllegalArgumentException: Service not registered**
```
Caused by: java.lang.IllegalArgumentException: Service not registered: cc.netpas.android_firewall.service.VpnConnectionService$1@d8d3c03
                                                                                at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1049)
                                                                                at android.app.ContextImpl.unbindService(ContextImpl.java:1865)
                                                                                at android.content.ContextWrapper.unbindService(ContextWrapper.java:550)
                                                                                at cc.netpas.android_firewall.service.VpnConnectionService.onDestroy(VpnConnectionService.java:134)
                                                                                at android.app.ActivityThread.handleStopService(ActivityThread.java:3075)
                                                                                at android.app.ActivityThread.access$2200(ActivityThread.java:153) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
```

```
unbindService(mServiceConnection);
```

**Comment by HanteIsHante** [comment]
**查询官方文档中关于unbindService()这个方法的介绍：**
```
public abstract void unbindService (ServiceConnection conn)
 
Added in API level 1
Disconnect from an application service. You will no longer receive calls as the service is restarted, and the service is now allowed to stop at any time.
 
Parameters
conn	The connection interface previously supplied to bindService(). This parameter must not be null.
```

最后一句看到这个传入的conn参数不能为null，也就是必须有绑定存在，才能解绑，小项目中绑定成功后第一次点击解绑不会报错，解绑后这个参数就是null了，再次点击解绑就会报错，那么我们为**解绑加一个判断就可以了。**

**Comment by HanteIsHante** [comment]
多次调用  `unbindService(mServiceConnection);` 解绑造成
