### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/NewProjectSum#90]
```

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
       at cc.netpas.android_firewall.paydialog.PayDetail$15.run(PayDetail.java:1276)
       at java.lang.Thread.run(Thread.java:818)

```

**Comment by HanteIsHante** [comment]
**List.size()**   作非空 逻辑判断
