### ISSUE TITLE
Unable to add window -- token null is not for an application

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/NewProjectSum#95]
```
 android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
                                                                                   at android.view.ViewRootImpl.setView(ViewRootImpl.java:584)
                                                                                   at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:260)
                                                                                   at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                                                   at android.app.Dialog.show(Dialog.java:286)
                                                                                   at com.example.hante.rxjavamodel.MainActivity.onClick(MainActivity.java:375)
                                                                                   at com.example.hante.rxjavamodel.MainActivity_ViewBinding$3.doClick(MainActivity_ViewBinding.java:53)
                                                                                   at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                                   at android.view.View.performClick(View.java:4444)
                                                                                   at android.view.View$PerformClick.run(View.java:18440)
                                                                                   at android.os.Handler.handleCallback(Handler.java:733)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5016)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                                                                                   at dalvik.system.NativeStart.main(Native Method)

```
**Error Code**
```
 DialogShow.ShowDialog(MainActivity.this, new JSONObject()).show();
```

**Comment by HanteIsHante** [comment]
参考 #97

**Comment by HanteIsHante** [comment]
**Dialog(Context):**
context 不能是 application 级别，只能是当前 activity 或者 Service
