### ISSUE TITLE
 Dialog Show 

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/NewProjectSum#97]
```
Could not dispatch event: class cc.netpas.android_firewall.model.DialogShow to subscribing class class cc.netpas.android_firewall.a
android.util.AndroidRuntimeException: requestFeature() must be called before adding content
    at com.android.internal.policy.impl.PhoneWindow.requestFeature(PhoneWindow.java:249)
    at android.app.Dialog.requestWindowFeature(Dialog.java:1041)
    at cc.netpas.android_firewall.utils.DialogShowUtil.ShowDialog(DialogShowUtil.java:59)
    at cc.netpas.android_firewall.activities.BaseActivity.onMessageEvent(BaseActivity.java:239)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
    at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5016)
    at java.lang.reflect.Method.invokeNative(Native Method)

                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
    at dalvik.system.NativeStart.main(Native Method)
````

**Comment by HanteIsHante** [comment]
```
Could not dispatch event: class cc.netpas.android_firewall.model.DialogShow to subscribing class clas
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
    at android.os.Handler.<init>(Handler.java:200)
    at android.os.Handler.<init>(Handler.java:114)
    at android.app.Dialog.<init>(Dialog.java:109)
    at android.app.Dialog.<init>(Dialog.java:133)
    at cc.netpas.android_firewall.activities.BaseActivity.ShowDialog(BaseActivity.java:251)
    at cc.netpas.android_firewall.activities.BaseActivity.onMessageEvent(BaseActivity.java:247)
    at java.lang.reflect.Method.invokeNative(Native Method)

                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
    at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
Could not dispatch event: class cc.netpas.android_firewall.model.DialogShow to subscribing class clas
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
    at android.os.Handler.<init>(Handler.java:200)
    at android.os.Handler.<init>(Handler.java:114)
    at android.app.Dialog.<init>(Dialog.java:109)
    at android.app.Dialog.<init>(Dialog.java:133)
    at cc.netpas.android_firewall.activities.BaseActivity.ShowDialog(BaseActivity.java:251)
    at cc.netpas.android_firewall.activities.BaseActivity.onMessageEvent(BaseActivity.java:247)
    at java.lang.reflect.Method.invokeNative(Native Method)

                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
    at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
```

**Comment by HanteIsHante** [comment]
```
Dialog mDialog = new Dialog(mContext)

```

**Comment by HanteIsHante** [comment]
```
roid.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
 at android.view.ViewRootImpl.setView(ViewRootImpl.java:584)
 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:260)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
 at android.app.Dialog.show(Dialog.java:286)
 at cc.netpas.android_firewall.activities.BaseActivity.ShowDialog(BaseActivity.java:314)
 at cc.netpas.android_firewall.activities.BaseActivity.onMessageEvent(BaseActivity.java:247)
 at java.lang.reflect.Method.invokeNative(Native Method)

                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
 at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
 at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
 at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
 at android.os.Handler.dispatchMessage(Handler.java:102)

```

**Comment by HanteIsHante** [comment]
要创建对话框，您需要一个活动上下文或服务上下文，而不是应用程序上下文（getApplicationContext（）和getApplication（）都返回应用程序上下文）。

**Comment by HanteIsHante** [comment]
```
Dialog mDialog = new Dialog(mContext);
```
mContext 需要的是 **activity** 或 **service**  ，而**非 Application**
