### ISSUE TITLE
BuyQuotaActivity has leaked window 

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/NewProjectSum#98]
```
Activity cc.netpas.android_firewall.activities.BuyQuotaActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{41d8e878 V.E..... R.....ID 0,0-600,325} that was originally added here
android.view.WindowLeaked: Activity cc.netpas.android_firewall.activities.BuyQuotaActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{41d8e878 V.E..... R.....ID 0,0-600,325} that was originally added here
    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:353)
    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:239)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
    at android.app.Dialog.show(Dialog.java:281)
    at cc.netpas.android_firewall.activities.BaseActivity.ShowDialog(BaseActivity.java:308)
    at cc.netpas.android_firewall.activities.BaseActivity.onMessageEvent(BaseActivity.java:242)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
    at org

```

**Comment by HanteIsHante** [comment]
在您退出活动之前，在您创建的对话框中调用dismiss（），例如onPause（）或onDestroy（）

**Comment by HanteIsHante** [comment]
#99

**Comment by HanteIsHante** [comment]
如果多个弹出框(dialog) 同时展示，可通过list 集合来展示，跳转页面在(Stop) 中通过for循环来dismiss,再移除 list 集合

```
 Dialog dialog = ShowDialog(dialogShow.getJSONObject());
        mDialogs.add(dialog);
        for(Dialog dialog1 : mDialogs) {
            dialog1.show();
        }
```



```
 for(Dialog dialog : mDialogs) {
            if (dialog.isShowing()){
                dialog.dismiss();
            }
        }
        for(int i = (mDialogs.size() - 1); i >= 0; i--) {
            mDialogs.remove(i);
        }

```
